"""AI Insights page: generated narrative, anomalies and trend highlights."""

from __future__ import annotations

import streamlit as st

from components import cards, charts, theme
from utils import data_loader, indicators, insights, state

st.set_page_config(page_title="Lumina — AI Insights", page_icon="🤖",
                   layout="wide")


def main() -> None:
    app = state.sidebar(active="AI Insights")
    theme.banner("AI Insights",
                 f"Automated analysis of {app.ticker}'s recent behavior")

    frame = indicators.enrich(
        data_loader.fetch_history(app.ticker, period=app.period))
    if frame.empty:
        st.warning("No price history available.")
        return

    score, label = insights.sentiment_score(frame)
    generated = insights.generate(frame)

    left, right = st.columns([2, 1])

    with left:
        with st.container(border=True):
            theme.section("Generated analysis", "What the data is saying")
            for item in generated:
                st.markdown(
                    f"<div class='insight'><div class='ic'>{item.icon}</div>"
                    f"<div><p class='tt'>{item.title}</p>"
                    f"<p class='dd'>{item.detail}</p></div></div>",
                    unsafe_allow_html=True)

    with right:
        with st.container(border=True):
            theme.section("Sentiment", "Composite read")
            st.plotly_chart(charts.gauge(score, label, app.dark),
                            use_container_width=True)
            pos = sum(1 for i in generated if i.tone == "positive")
            neg = sum(1 for i in generated if i.tone == "negative")
            tone = "pos" if pos > neg else "neg" if neg > pos else "neu"
            st.markdown(
                cards.pill(f"{pos} bullish · {neg} bearish signals", tone),
                unsafe_allow_html=True)

    with st.container(border=True):
        theme.section("Context", "Price with detected signals")
        sigs = indicators.signal_crossovers(frame)
        st.plotly_chart(
            charts.candlestick(frame, app.dark, show_ma=(20, 50),
                               signals=sigs),
            use_container_width=True, config={"scrollZoom": True})

    st.info("These insights are generated by a deterministic rule engine over "
            "historical prices. They are educational and explicitly **not** "
            "investment advice.")


if __name__ == "__main__":
    main()
